#!/usr/bin/env python3
# -*- coding:utf-8 -*-

def main(林以諾):
    
    我的名字 = 林以諾[0:7] 
    我的學號 = 林以諾[8:17]
    基本資料 = 我的名字 + 我的學號
    
    print(基本資料)
    
    林以諾LIST = 林以諾.split(" ")
    
    print(林以諾LIST)
    print("私の名前：{}".format(林以諾LIST[0]))
    print("私の学籍番号：{}".format(林以諾LIST[1]))
    
if __name__ == "__main__":
    nameSTR= "林·イーノック 40992022M"
    
    main(nameSTR)
